# Generated by Django 5.1.7 on 2025-04-10 07:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goods_time_create_alter_goods_time_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['-time_create'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=autoslug.fields.AutoSlugField(max_length=127, unique=True, verbose_name='URL'),
        ),
    ]
