# Generated by Django 5.1.7 on 2025-04-10 07:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_goods_options_alter_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=127, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
