# Generated by Django 5.1.7 on 2025-04-10 07:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=127, populate_from='name', unique=True, verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
