# Generated by Django 5.1.7 on 2025-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_goods_slug_alter_goods_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=127, unique=True, verbose_name='URL'),
        ),
    ]
