# Generated by Django 5.1.7 on 2025-04-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_goods_condition_alter_goods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='condition',
            field=models.BooleanField(default=True),
        ),
    ]
