# Generated by Django 5.1.7 on 2025-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_goods_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True, verbose_name='Название')),
                ('address', models.CharField(max_length=127, unique=True, verbose_name='Адрес')),
                ('link_to_map', models.URLField(max_length=127, unique=True, verbose_name='Ссылка на карту')),
            ],
        ),
    ]
