# Generated by Django 5.1.7 on 2025-04-29 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.address', verbose_name='Адрес'),
        ),
    ]
