# Generated by Django 5.1.7 on 2025-04-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_goods_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(blank=True, max_length=127, null=True, unique=True, verbose_name='slug'),
        ),
    ]
