# Generated by Django 5.1.7 on 2025-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_address_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Цена'),
        ),
    ]
