# Generated by Django 5.1.7 on 2025-05-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_address_name_alter_goods_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=127, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=127, null=True, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='condition',
        ),
    ]
