# Generated by Django 5.1.7 on 2025-05-07 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_condition_remove_goods_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='goods.condition', verbose_name='Состояние'),
            preserve_default=False,
        ),
    ]
