# Generated by Django 5.1.7 on 2025-04-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Контактный телефон'),
        ),
    ]
