# Generated by Django 5.1.7 on 2025-05-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на телеграмм'),
        ),
    ]
