# Generated by Django 5.1.7 on 2025-05-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на телеграмм'),
        ),
    ]
